### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by zeGrandpa** [saracalafuri/streaming-mamma#1]
Le site utilise du bootsrap !

**Comment by zeGrandpa** [comment]
Le boostrap est une aberration, le style de la page devrait rester dans le css et le corps de la page dans le html!
Des classe "text-center" ne devrait pas se trouver dans le code html, il faudrait affecter, la propriété dans le css 👍

**Comment by saracalafuri** [comment]
Et si je créé des classes dans le fichier html et que je définis le bootstrap dans le fichier css, ça résout le problème non ?
