### ISSUE TITLE
Git ne sert à rien

### ISSUE THREAD

**Issue by zeGrandpa** [saracalafuri/streaming-mamma#2]
si on ne push jamais et qu'on utilise pas les fonctionnalités de gestion de version qu'il propose...

**Comment by saracalafuri** [comment]
Oui c'est ma faute ! Je push demain !

**Comment by zeGrandpa** [comment]
À ce que je sache, vous êtes deux à avoir travaillé dessus, non ?

**Comment by saracalafuri** [comment]
Oui en effet, directement sur la Pi.

**Comment by zeGrandpa** [comment]
Vous devriez installer git dessus.

**Comment by saracalafuri** [comment]
Ça prend pas trop de place ?

**Comment by zeGrandpa** [comment]
Non t'en fais pas, mais ce qui serait encore mieux, ce serai de mettre un serveur web sur ton pc 👍

**Comment by zeGrandpa** [comment]
Alors, il vient ce commit ?
